version: "3"
services:
  db_test:
    container_name: db_test
    image: postgres
    restart: always
    ports:
      - 2345:5432
    env_file: .env.test
    healthcheck:
      test: pg_isready -U postgres

  node_app_tests:
    container_name: node_app_tests
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 5000:5000
    depends_on:
      db_test:
        condition: service_healthy

    env_file: .env.test
