name: DidiCiTests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  DidiCiTests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "primeflix_test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@db_test:5432/didi_test?schema=public"
          directory: didi_ci
          file_name: .env.test

      - name: Run tests
        run: docker-compose -f didi_ci/docker-compose.test.yml up --exit-code-from node_app_tests
